/* notify-copy — the voice of the txn_review notification.
 *
 * The push payload carries NO amount, NO merchant, NO category name. Context
 * (category concept × amount tier × daypart × an optional merchant-keyword
 * pool) is distilled HERE, at the only moment the pipeline holds the plaintext,
 * into a tiny enum meta {c, t, d, p}. push-send turns that meta into one
 * pre-written line, so what transits Apple/Google/Mozilla asserts nothing
 * private.
 *
 * SHAPE (2026-09-05): every line is a pair { e, b } —
 *   • e = the TITLE: exactly one face emoji, the app's reaction,
 *   • b = the BODY: plain text ending in "!", NO emoji, NO digits, ≤ 9 words.
 * VOICE: a fond, slightly nosy friend reacting to THIS one transaction —
 * playful judgment PLUS a smart nudge to spend/live wisely or healthily, never
 * preachy, never about the queue.
 *
 * DAYPART: for the time-sensitive concepts (Dining, Groceries) and the coffee /
 * milk-tea pools, a daypart line (sáng/trưa/chiều/tối, from occurred_at) is used
 * when a real clock time is known; a date-only row falls back to the tier line.
 *
 * THE TABLES LEFT (2026-09-30, notification-activation-spec.md §6). The lines and
 * the selection logic now live in taxonomy/notify-lines.json, generated by
 * tools/gen-notify-lines.js into ./notify-lines.mjs for this side and
 * src/js-ui/14-notify-lines.js for the browser. The permission sheet previews the
 * line the person would actually receive, which is only honest while both sides
 * pick the same one — so there is exactly one copy of both. This module keeps its
 * public surface and nothing else: copyMeta, reviewBody, digestBody, statementBody,
 * same signatures, same behaviour. */

import { metaOf, bodyOf, digestOf, statementOf } from './notify-lines.mjs';

/* The whole plaintext → the tiny enum that leaves this process.
 * c: concept | 'income' | 'unknown' · t: 1..4 · d: daypart | absent · p: pool.
 *
 * THE TREE NODE (0144, `extraction.node`) is read only to fill what the
 * extractor left empty: a node's concept (conceptOf) stands in for a missing
 * category, and its pool attribute (poolOf) for a missing pool. The payload
 * shape does not change — still {c,t,d,p}, still no amount, no merchant, no
 * category NAME, and no node code either: a code like 'coffee' is exactly the
 * kind of specific claim this payload exists not to carry. */
export function copyMeta(extraction) {
  return metaOf(extraction);
}

/* meta {c,t,d,p} → { title: emoji, body: text! } about THIS transaction. Pool
 * wins (with a daypart variant if the pool has one), then a concept daypart
 * override, then the tier line. A missing cell degrades to unknown/t2. */
export function reviewBody(meta, lang, rnd) {
  return bodyOf(meta, lang, rnd);
}

/* The one-time backfill digest — the single line allowed a number (a batch
 * size is not private). Same {title, body} shape; face in the title. */
export function digestBody(count, lang) {
  return digestOf(count, lang);
}

/* A statement arrived. Its own line because it asks for something different: a
 * transaction push asks for one tap, this asks for a few minutes and perhaps a
 * password, and a generic "something is waiting" followed by a password prompt
 * reads as a bait-and-switch (statement-capture-spec.md, decision S26). Carries
 * NOTHING: no bank (where someone banks is itself private), no count, no period. */
export function statementBody(lang) {
  return statementOf(lang);
}
