# GENERATED by `make sync-shared` from shared/accounts.py — do not edit.
"""Per-user Gmail credentials and history checkpoints.

The pipeline is multi-user: a notification names a mailbox, and this module
answers "what are that mailbox's credentials, and where did we get to last
time". Where those live is deliberately behind an interface — the Postgres
implementation lands later without touching main.py.

Two rules the backing store must honour, whatever it ends up being:

* A refresh token grants unlimited read access to someone's mail. It must be
  encrypted at rest and must never reach a log line.
* `historyId` is a per-mailbox cursor. It is written only after the messages
  in that window are handled, so a crash replays rather than skips.
"""

import logging
import os
from typing import Protocol

log = logging.getLogger(__name__)

# OAuth scope this pipeline needs. Read-only on purpose: nothing here sends,
# modifies or deletes mail, and a narrower scope is a smaller blast radius if
# a token leaks.
SCOPES = ["https://www.googleapis.com/auth/gmail.readonly"]


class UnknownMailbox(Exception):
    """No account on file for this address.

    Permanent: the notification is acked rather than retried. It happens when
    a user disconnects Gmail but their watch has not expired yet.
    """


class Account(Protocol):
    """What the store returns for one mailbox."""

    email: str
    refresh_token: str
    history_id: str | None


class AccountStore(Protocol):
    """The seam. A Postgres-backed implementation replaces InMemoryStore with
    no change to its callers."""

    def get(self, email: str) -> Account:
        """Credentials and cursor for one mailbox.

        Raises UnknownMailbox if the address is not connected.
        """
        ...

    def save_history_id(self, email: str, history_id: str) -> None:
        """Advance the cursor, after the work for that window succeeded."""
        ...

    def list_connected(self) -> list[str]:
        """Addresses of every mailbox still connected.

        Used by the watch-renewal job, which has to touch all of them: a Gmail
        watch lapses after 7 days and takes the notifications with it.
        """
        ...


class _Account:
    __slots__ = ("email", "refresh_token", "history_id")

    def __init__(self, email: str, refresh_token: str, history_id: str | None = None):
        self.email = email
        self.refresh_token = refresh_token
        self.history_id = history_id

    def __repr__(self) -> str:
        # Never let the token near a log line or a traceback.
        return f"<Account {self.email} history_id={self.history_id}>"


class InMemoryStore:
    """Stand-in until the Postgres store exists.

    Seeded from GMAIL_ACCOUNTS, a JSON object of {email: refresh_token}. State
    dies with the instance, so a saved historyId does not survive a cold start
    — fine for wiring the pipeline up, not for running it.
    """

    def __init__(self, seed: dict[str, str] | None = None):
        self._accounts: dict[str, _Account] = {
            email: _Account(email, token) for email, token in (seed or {}).items()
        }

    def get(self, email: str) -> Account:
        try:
            return self._accounts[email]
        except KeyError:
            raise UnknownMailbox(email) from None

    def save_history_id(self, email: str, history_id: str) -> None:
        account = self._accounts.get(email)
        if account is None:
            raise UnknownMailbox(email)
        account.history_id = history_id

    def list_connected(self) -> list[str]:
        return list(self._accounts)


def _seed_from_env() -> dict[str, str]:
    """Read GMAIL_ACCOUNTS, tolerating absence and malformed JSON.

    A bad value must not take the function down at import time; it is logged
    and treated as "no accounts connected".
    """
    import json  # noqa: PLC0415

    raw = os.environ.get("GMAIL_ACCOUNTS")
    if not raw:
        return {}
    try:
        parsed = json.loads(raw)
    except ValueError as exc:
        log.error("GMAIL_ACCOUNTS is not valid JSON: %s", exc)
        return {}
    if not isinstance(parsed, dict):
        log.error("GMAIL_ACCOUNTS must be a JSON object of {email: refresh_token}")
        return {}
    return {str(k): str(v) for k, v in parsed.items()}


def default_store() -> AccountStore:
    """The store this deployment uses.

    Swap the body for the Postgres implementation when it exists; callers keep
    working because they only ever see the AccountStore protocol.
    """
    return InMemoryStore(_seed_from_env())