"""Turning a fetched mail body into the text the parser reads.

Two steps, in this order:

    strip_html   HTML  -> text     what is in the mail
    declutter    text  -> text     what of it is the notice

Both belong to INGEST, not to the parser. What Gmail hands over is a 4.5MB
HTML document; what the parser needs is about 3KB of text. Normalising before
publishing keeps that 1500x off the Pub/Sub topic — a mail with enough inline
images can otherwise approach the 10MB message limit, and a transaction that
does not fit is a transaction lost.

Everything downstream of the topic then has one input contract: `body` is
normalised text. The parser does not care whether a mail arrived as HTML or as
plain text, and a second source — a forwarded mail, a webhook — normalises its
own input rather than teaching the parser another shape.

Not here, and deliberately: `llm._clip` and `masking.mask`. Those serve the
model — a token budget and a network boundary — and neither is knowledge this
function has. Masking here would also take away the figures the parser's
deterministic stage reads.
"""

import logging
import re

from bs4 import BeautifulSoup

log = logging.getLogger(__name__)

# value and the next label — flatten it to a space and a value runs on until
# the parser's window ends, which read a cinema's whole street address as its
# name.
#
# Punctuation rather than a newline: `spec._after_label` already skips a run of
# `[\s:.·|]` after a label, so this costs nothing where a value is bounded
# some other way, and everything where it is not.
_FIELD_BREAK = " · "

# Tags carrying no text a reader would see. Dropped whole, contents included —
# `get_text` would otherwise pull CSS rules and script source into the body.
_INVISIBLE = ("script", "style", "head", "title", "meta", "link", "noscript")

# Tags that end one field and begin another. Everything else — b, strong, span,
# a, em, font, i, u — is styling applied *within* a value, and breaking on it
# splits the value.
_BLOCK = (
    "td", "th", "tr", "table", "div", "p", "li", "ul", "ol", "br", "hr",
    "h1", "h2", "h3", "h4", "h5", "h6", "blockquote", "pre", "section", "article",
)

# Runs of the marker left adjacent once empty cells collapse.
_MARKER_RUN = re.compile(r"(?:·[ \t]*){2,}")

# One or more line endings, with any padding around them. In a plain-text body
# this is the only structure there is; in an HTML one it is what a template's
# source formatting leaves behind, which is harmless because the block tags
# have already marked the real boundaries.
_LINE_END = re.compile(r"[ \t]*\n[ \t\n]*")


def strip_html(body: str) -> str:
    """Flatten an HTML mail body to plain text, one field per boundary.

    BeautifulSoup over lxml rather than regexes over tags. Mail HTML is
    generated by Outlook, Gmail and a dozen bank templating systems, and is
    unclosed, mis-nested and full of conditional comments; a forgiving parser
    is the difference between "mostly works" and "works on the mail that
    actually arrives". The regex version this replaces had already grown two
    patterns and was accruing a third.

    Entity decoding, comment removal and attribute stripping all come free
    with the parse. What has to be asked for is the field boundary — see
    `_FIELD_BREAK`.

    Never raises: a body that will not parse at all comes back as the empty
    string, which the caller already treats as an unreadable mail. Throwing
    here would turn one malformed mail into a redelivery loop.
    """
    if not body:
        return ""

    try:
        soup = BeautifulSoup(body, "lxml")
    except Exception as exc:  # noqa: BLE001
        log.warning("could not parse mail body as HTML: %s", exc)
        return ""

    for tag in soup(_INVISIBLE):
        tag.decompose()

    # The break goes on block elements only. `get_text(separator=...)` puts one
    # between every *string*, which breaks on inline markup too — a bank that
    # emboldens its amount writes `<b>391.500</b> <span>đ</span>`, and that
    # came out as two fields; `<a>` around an address split it from its
    # angle brackets. Inline tags are styling, and styling is not structure.
    for tag in soup.find_all(_BLOCK):
        tag.insert_before(_FIELD_BREAK)
        tag.insert_after(_FIELD_BREAK)

    text = soup.get_text()

    # A line ending is a field boundary too, and in a text/plain body it is the
    # ONLY one — Gmail hands over the plain part when a mail has one, and those
    # carry no tags at all. Collapsing every newline to a space there merged
    # each label into the value below it: `Tổng tiền` came back as
    # `165.000đ Giá vé 165.000đ Bảo hiểm 0đ`, one field swallowing four.
    #
    # Done before whitespace is collapsed, because that is what destroys them.
    text = _LINE_END.sub(_FIELD_BREAK, text)

    text = re.sub(r"[^\S\n]+", " ", text)
    text = _MARKER_RUN.sub("· ", text)
    return text.strip().strip("· ").strip()

# Characters that carry no meaning anywhere, in any language: zero-width
# joiners and spaces, soft hyphens, byte-order marks, directionality marks.
# Mail templates use them for layout tricks and preheader padding, and they
# survive every other step because they are technically text.
_INVISIBLE_CHARS = re.compile(r"[\u00ad\u200b-\u200f\u2028\u2029\u202a-\u202e\ufeff]")

# A URL. Dropped rather than shortened: nothing downstream reads one, and a
# tracking link in a bank mail routinely runs to several hundred characters.
_URL = re.compile(r"https?://\S+|www\.[^\s·]+", re.IGNORECASE)

# What is left of an image once the tag is gone, plus any base64 run that
# survived. Both are machine noise with no reader-visible meaning.
_TECHNICAL = re.compile(r"\bcid:\S+|\bdata:[^\s·]{40,}|[A-Za-z0-9+/]{120,}={0,2}")

_MARKER = "·"


def declutter(text: str) -> str:
    """Drop what carries no meaning, and nothing else.

    Deliberately NOT a footer remover. An earlier version cut the body at the
    first line opening a boilerplate block — "Chính sách hoàn", "Tổng đài",
    "Điều khoản" — and that was wrong in a way worth recording, because it
    looked like it worked:

    * The 28 phrases it matched were read off four MoMo receipts. Nothing in
      them was true of a bank. Techcombank, VPBank and VNPAY word their tails
      differently, and some do it in English.
    * The failure was asymmetric. A tail that did not match cost some tokens;
      a phrase that matched EARLY cost the transaction. A notice printing
      "Tổng đài 1900 588 822" mid-body loses every field below it, silently.
    * It was deciding what a mail MEANS from a keyword list, which is the one
      job this pipeline already hands to a model precisely because keyword
      lists do not survive a template change.

    What is left is only what is safe on a mail nobody has seen yet:
    invisible characters, URLs, and technical residue. None of it depends on
    the sender, the wording or the language.

    Trimming to a token budget stays where it belongs, in `llm._clip`, which
    picks its window by where the transaction-shaped text actually is rather
    than by what the tail happens to be called.
    """
    if not text:
        return ""

    text = _INVISIBLE_CHARS.sub("", text)
    text = _URL.sub(" ", text)
    text = _TECHNICAL.sub(" ", text)

    text = _drop_repeats(text)

    text = re.sub(r"\s+", " ", text)
    text = _MARKER_RUN.sub("· ", text)
    return text.strip().strip("· ").strip()


def _drop_repeats(text: str) -> str:
    """Collapse a field repeated back to back.

    Mail templates emit the same line twice routinely: a preheader echoing the
    subject, a heading rendered once for wide screens and once for narrow. The
    check is on ADJACENT fields only — a figure legitimately appearing twice in
    different rows is not a repeat, and dropping it would take a real value.
    """
    kept: list[str] = []
    for field in text.split(_MARKER):
        value = field.strip()
        if value and kept and value == kept[-1].strip():
            continue
        kept.append(field)
    return _MARKER.join(kept)
