"""Copy shared modules into the functions that declare them.

Each function's pyproject.toml names what it needs:

    [tool.earthy]
    shared = ["accounts.py", "gmail_auth.py"]

The copies land beside main.py as top-level modules, which is how Google's
local-dependency guidance expects a vendored module to be laid out. They are
generated and carry a `# GENERATED` header: shared/ is the only place to edit
them.

Run from the workspace root (the Makefile does).
"""

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "shared"
FUNCTIONS = ROOT / "functions"

BANNER = "# GENERATED by `make sync-shared` from shared/{name} — do not edit.\n"


def declared(pyproject: Path) -> list[str]:
    with pyproject.open("rb") as handle:
        config = tomllib.load(handle)
    return config.get("tool", {}).get("earthy", {}).get("shared", [])


def sync_one(function_dir: Path, names: list[str], errors: list[str]) -> int:
    written = 0
    for name in names:
        source = SHARED / name
        if not source.exists():
            errors.append(f"{function_dir.name}: shared/{name} does not exist")
            continue

        target = function_dir / name
        # A file the function owns must never be silently replaced by a
        # same-named shared module.
        if target.exists() and not target.read_text().startswith("# GENERATED"):
            errors.append(
                f"{function_dir.name}: {name} already exists and is not generated "
                f"— rename one of them"
            )
            continue

        body = BANNER.format(name=name) + source.read_text()
        if target.exists() and target.read_text() == body:
            continue  # unchanged: leave the mtime alone
        target.write_text(body)
        written += 1
    return written


def main() -> int:
    if not SHARED.is_dir():
        print(f"no shared/ directory at {SHARED}", file=sys.stderr)
        return 1

    errors: list[str] = []
    total = 0
    for pyproject in sorted(FUNCTIONS.glob("*/pyproject.toml")):
        names = declared(pyproject)
        if names:
            total += sync_one(pyproject.parent, names, errors)

    for error in errors:
        print(f"error: {error}", file=sys.stderr)
    if errors:
        return 1

    print(f"sync-shared: {total} file(s) updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
