#!/usr/bin/env node
/* gen-brands — ONE registry, one target (the client).
   taxonomy/brands.json is the brand registry for recognisable recurring
   services (recurring-charges-spec.md §3.3, RR22): one entry per brand with
   the words that identify it in a payee, a memo or a receipt signature, the
   Simple Icons glyph it wears and that brand's own colour.
   Generated, never hand-edited:
     src/js-ui/08-brands.js   classic script → window.FH_BRANDS
   The glyph paths are inlined from taxonomy/brand-glyphs/<slug>.svg (CC0), so
   the app ships them and fetches nothing: which services a person pays is
   theirs, and a logo request per row would say it to a third party.
   Rules enforced here: keys unique and [a-z0-9]+; every glyph file exists and
   holds one <path>; hex is six hex digits; match words lower-case, folded,
   never empty, never claimed by two brands; a rail (how the money moved:
   ZaloPay, VNPay, Google Pay) is folded and is never a brand's match word;
   a biller (who collects for many products: Apple's billing line, Google
   Play, PayPal) is folded. A biller MAY be a brand's word too: Apple is both
   a logo worth showing and a payee that says nothing about what was bought
   (recurring-charges-spec.md §19.3).

   Since RR23 the registry also faces every ledger row and queue card, so the
   matcher is strict where it used to be loose: a word must START a token
   ("hbo" does not match inside another word), rails are struck from a text
   before it is read ("ZALOPAY_Chickita" is not Zalo), and results are
   remembered per text because a list asks for the same strings again on
   every paint. */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'taxonomy', 'brands.json');
const GLYPHS = path.join(ROOT, 'taxonomy', 'brand-glyphs');

const fold = (s) => String(s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'd').toLowerCase().trim();

function load() {
  const reg = JSON.parse(fs.readFileSync(SRC, 'utf8'));
  const keys = new Set(), words = new Map(), glyphs = {};
  for (const b of reg.brands) {
    if (!/^[a-z0-9]+$/.test(b.key)) throw new Error('brands: bad key ' + b.key);
    if (keys.has(b.key)) throw new Error('brands: duplicate key ' + b.key);
    keys.add(b.key);
    if (!b.label) throw new Error('brands: ' + b.key + ' has no label');
    if (!/^[0-9A-Fa-f]{6}$/.test(b.hex)) throw new Error('brands: ' + b.key + ' bad hex ' + b.hex);
    if (!Array.isArray(b.match) || !b.match.length) throw new Error('brands: ' + b.key + ' has no match words');
    for (const w of b.match) {
      const f = fold(w);
      if (!f || f !== w) throw new Error('brands: ' + b.key + ' match word must be folded lower-case: "' + w + '"');
      if (words.has(f) && words.get(f) !== b.key) throw new Error('brands: word "' + w + '" claimed by ' + words.get(f) + ' and ' + b.key);
      words.set(f, b.key);
    }
    if (!glyphs[b.glyph]) {
      const file = path.join(GLYPHS, b.glyph + '.svg');
      if (!fs.existsSync(file)) throw new Error('brands: ' + b.key + ' glyph file missing: ' + b.glyph + '.svg');
      const svg = fs.readFileSync(file, 'utf8');
      const m = svg.match(/<path d="([^"]+)"/);
      if (!m) throw new Error('brands: ' + b.glyph + '.svg has no path');
      if ((svg.match(/<path/g) || []).length !== 1) throw new Error('brands: ' + b.glyph + '.svg must hold exactly one path');
      glyphs[b.glyph] = m[1];
    }
  }
  const rails = reg.rails || [];
  for (const r of rails) {
    const f = fold(r);
    if (!f || f !== r) throw new Error('brands: rail must be folded lower-case: "' + r + '"');
    if (words.has(f)) throw new Error('brands: rail "' + r + '" is also a match word of ' + words.get(f));
  }
  const billers = reg.billers || [];
  for (const r of billers) { if (!fold(r) || fold(r) !== r) throw new Error('brands: biller must be folded lower-case: "' + r + '"'); }
  return { reg, glyphs, rails, billers };
}

function clientJs(reg, glyphs, rails, billers) {
  const data = { version: reg.version, brands: reg.brands.map((b) => ({ key: b.key, label: b.label, glyph: b.glyph, hex: b.hex, match: b.match })), rails: (rails || []).slice().sort((a, c) => c.length - a.length), billers: (billers || []).slice(), glyphs };
  return '/* GENERATED by tools/gen-brands.js from taxonomy/brands.json + taxonomy/brand-glyphs/ — do not edit.\n' +
    '   window.FH_BRANDS: recognisable recurring services, their glyph (Simple Icons, CC0) and colour. Version ' + reg.version + '. */\n' +
    'var FH_BRANDS = (function () {\n  var DATA = ' + JSON.stringify(data) + ';\n' +
    '  var BY = {}, i; for (i = 0; i < DATA.brands.length; i++) BY[DATA.brands[i].key] = DATA.brands[i];\n' +
    '  /* longest match word first, so "youtube premium" beats "youtube" and "google one" beats "google" */\n' +
    '  var WORDS = []; for (i = 0; i < DATA.brands.length; i++) { var b = DATA.brands[i]; for (var j = 0; j < b.match.length; j++) WORDS.push([b.match[j], b.key]); }\n' +
    '  WORDS.sort(function (a, c) { return c[0].length - a[0].length; });\n' +
    '  function fold(s) { s = String(s == null ? "" : s); if (s.normalize) s = s.normalize("NFD").replace(/[\\u0300-\\u036f]/g, ""); return s.replace(/\\u0111/g, "d").replace(/\\u0110/g, "d").toLowerCase(); }\n' +
    '  /* how the money moved is not who was paid: rails leave the text first */\n' +
    '  var RAILS = DATA.rails || [];\n' +
    '  function strip(s) { for (var r = 0; r < RAILS.length; r++) { if (s.indexOf(RAILS[r]) >= 0) s = s.split(RAILS[r]).join(" "); } return s; }\n' +
    '  /* a word counts only where a token starts: "hbo" in "nhbo" is not HBO, "grab" in "grabfood" is Grab */\n' +
    '  function has(s, w) { var i = s.indexOf(w); while (i >= 0) { if (i === 0 || !/[a-z0-9]/.test(s.charAt(i - 1))) return true; i = s.indexOf(w, i + 1); } return false; }\n' +
    '  var MEMO = {}, MEMO_N = 0;\n' +
    '  function one(text) {\n' +
    '    var raw = String(text == null ? "" : text); if (!raw) return null;\n' +
    '    if (Object.prototype.hasOwnProperty.call(MEMO, raw)) return MEMO[raw];\n' +
    '    var s = fold(raw), key = null;\n' +
    '    /* a receipt signature names the product itself and is never a rail */\n' +
    '    if (s.indexOf("sub|") !== 0 && s.indexOf("store|") !== 0) s = strip(s);\n' +
    '    for (var w = 0; w < WORDS.length; w++) { if (has(s, WORDS[w][0])) { key = WORDS[w][1]; break; } }\n' +
    '    if (MEMO_N > 4000) { MEMO = {}; MEMO_N = 0; }\n' +
    '    MEMO[raw] = key; MEMO_N++; return key;\n' +
    '  }\n' +
    '  /* The brand for a charge. `texts` are tried in order (receipt signature,\n     then payee, then memo): the first text with any match wins, and within a\n     text the longest word wins. → { key, label, hex, path } or null. */\n' +
    '  function match(texts) {\n' +
    '    for (var t = 0; t < (texts || []).length; t++) { var k = one(texts[t]); if (k) return get(k); }\n' +
    '    return null;\n  }\n' +
    '  /* Is this payee a BILLER: someone who collects for many products, so the\n     string says nothing about what was bought (recurring-charges-spec §19.3)?\n     A listed biller, or a payment rail with no merchant left beside it. */\n' +
    '  var BILLERS = DATA.billers || [];\n' +
    '  function isBiller(text) {\n' +
    '    var s = fold(text); if (!s) return false;\n' +
    '    for (var b = 0; b < BILLERS.length; b++) { if (has(s, BILLERS[b])) return true; }\n' +
    '    var bare = strip(s); if (bare === s) return false;\n' +
    '    return bare.replace(/[^a-z]+/g, "").length < 3;\n' +
    '  }\n' +
    '  /* The brand a LEDGER ROW or QUEUE CARD wears (RR23). A row filed under a\n     person (the p2p branch) or under anything that is not spending wears none:\n     a person is not a shop, whatever the memo mentions. */\n' +
    '  function forRow(r) {\n' +
    '    if (!r) return null;\n' +
    '    var T = (typeof FH_TAX !== "undefined") ? FH_TAX : null;\n' +
    '    if (r.node && T && T.get && T.get(r.node)) { if (T.kindOf(r.node) !== "expense" || T.root(r.node) === "p2p") return null; }\n' +
    '    return match([r.sig, r.payee, r.note, r.provider]);\n' +
    '  }\n' +
    '  function get(key) { var b = BY[key]; return b ? { key: b.key, label: b.label, hex: b.hex, path: DATA.glyphs[b.glyph] } : null; }\n' +
    '  /* One tile: white glyph on the brand\'s colour. `size` in px. */\n' +
    '  function svg(b, size) { return \'<svg viewBox="0 0 24 24" width="\' + (size || 24) + \'" height="\' + (size || 24) + \'" aria-hidden="true"><path fill="currentColor" d="\' + b.path + \'"/></svg>\'; }\n' +
    '  return { version: DATA.version, match: match, forRow: forRow, isBiller: isBiller, get: get, svg: svg, all: function () { return DATA.brands.slice(); } };\n' +
    '})();\nwindow.FH_BRANDS = FH_BRANDS;';
}

function generate() {
  const { reg, glyphs, rails, billers } = load();
  const out = path.join(ROOT, 'src', 'js-ui', '08-brands.js');
  const text = clientJs(reg, glyphs, rails, billers);
  if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== text) fs.writeFileSync(out, text);
  return reg.brands.length;
}
if (require.main === module) console.log('gen-brands: ' + generate() + ' brands');
module.exports = { generate };
