#!/usr/bin/env node
/* gen-brands — ONE registry, one target (the client).
   taxonomy/brands.json is the brand registry for recognisable recurring
   services (recurring-charges-spec.md §3.3, RR22): one entry per brand with
   the words that identify it in a payee, a memo or a receipt signature, the
   Simple Icons glyph it wears and that brand's own colour.
   Generated, never hand-edited:
     src/js-ui/08-brands.js   classic script → window.FH_BRANDS
   The glyph paths are inlined from taxonomy/brand-glyphs/<slug>.svg (CC0), so
   the app ships them and fetches nothing: which services a person pays is
   theirs, and a logo request per row would say it to a third party.
   Rules enforced here: keys unique and [a-z0-9]+; every glyph file exists and
   holds one <path>; hex is six hex digits; match words lower-case, folded,
   never empty, never claimed by two brands. */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'taxonomy', 'brands.json');
const GLYPHS = path.join(ROOT, 'taxonomy', 'brand-glyphs');

const fold = (s) => String(s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'd').toLowerCase().trim();

function load() {
  const reg = JSON.parse(fs.readFileSync(SRC, 'utf8'));
  const keys = new Set(), words = new Map(), glyphs = {};
  for (const b of reg.brands) {
    if (!/^[a-z0-9]+$/.test(b.key)) throw new Error('brands: bad key ' + b.key);
    if (keys.has(b.key)) throw new Error('brands: duplicate key ' + b.key);
    keys.add(b.key);
    if (!b.label) throw new Error('brands: ' + b.key + ' has no label');
    if (!/^[0-9A-Fa-f]{6}$/.test(b.hex)) throw new Error('brands: ' + b.key + ' bad hex ' + b.hex);
    if (!Array.isArray(b.match) || !b.match.length) throw new Error('brands: ' + b.key + ' has no match words');
    for (const w of b.match) {
      const f = fold(w);
      if (!f || f !== w) throw new Error('brands: ' + b.key + ' match word must be folded lower-case: "' + w + '"');
      if (words.has(f) && words.get(f) !== b.key) throw new Error('brands: word "' + w + '" claimed by ' + words.get(f) + ' and ' + b.key);
      words.set(f, b.key);
    }
    if (!glyphs[b.glyph]) {
      const file = path.join(GLYPHS, b.glyph + '.svg');
      if (!fs.existsSync(file)) throw new Error('brands: ' + b.key + ' glyph file missing: ' + b.glyph + '.svg');
      const svg = fs.readFileSync(file, 'utf8');
      const m = svg.match(/<path d="([^"]+)"/);
      if (!m) throw new Error('brands: ' + b.glyph + '.svg has no path');
      if ((svg.match(/<path/g) || []).length !== 1) throw new Error('brands: ' + b.glyph + '.svg must hold exactly one path');
      glyphs[b.glyph] = m[1];
    }
  }
  return { reg, glyphs };
}

function clientJs(reg, glyphs) {
  const data = { version: reg.version, brands: reg.brands.map((b) => ({ key: b.key, label: b.label, glyph: b.glyph, hex: b.hex, match: b.match })), glyphs };
  return '/* GENERATED by tools/gen-brands.js from taxonomy/brands.json + taxonomy/brand-glyphs/ — do not edit.\n' +
    '   window.FH_BRANDS: recognisable recurring services, their glyph (Simple Icons, CC0) and colour. Version ' + reg.version + '. */\n' +
    'var FH_BRANDS = (function () {\n  var DATA = ' + JSON.stringify(data) + ';\n' +
    '  var BY = {}, i; for (i = 0; i < DATA.brands.length; i++) BY[DATA.brands[i].key] = DATA.brands[i];\n' +
    '  /* longest match word first, so "youtube premium" beats "youtube" and "google one" beats "google" */\n' +
    '  var WORDS = []; for (i = 0; i < DATA.brands.length; i++) { var b = DATA.brands[i]; for (var j = 0; j < b.match.length; j++) WORDS.push([b.match[j], b.key]); }\n' +
    '  WORDS.sort(function (a, c) { return c[0].length - a[0].length; });\n' +
    '  function fold(s) { s = String(s == null ? "" : s); if (s.normalize) s = s.normalize("NFD").replace(/[\\u0300-\\u036f]/g, ""); return s.replace(/\\u0111/g, "d").replace(/\\u0110/g, "d").toLowerCase(); }\n' +
    '  /* The brand for a charge. `texts` are tried in order (receipt signature,\n     then payee, then memo): the first text with any match wins, and within a\n     text the longest word wins. → { key, label, hex, path } or null. */\n' +
    '  function match(texts) {\n' +
    '    for (var t = 0; t < (texts || []).length; t++) {\n' +
    '      var s = fold(texts[t]); if (!s) continue;\n' +
    '      for (var w = 0; w < WORDS.length; w++) { if (s.indexOf(WORDS[w][0]) >= 0) return get(WORDS[w][1]); }\n' +
    '    }\n    return null;\n  }\n' +
    '  function get(key) { var b = BY[key]; return b ? { key: b.key, label: b.label, hex: b.hex, path: DATA.glyphs[b.glyph] } : null; }\n' +
    '  /* One tile: white glyph on the brand\'s colour. `size` in px. */\n' +
    '  function svg(b, size) { return \'<svg viewBox="0 0 24 24" width="\' + (size || 24) + \'" height="\' + (size || 24) + \'" aria-hidden="true"><path fill="currentColor" d="\' + b.path + \'"/></svg>\'; }\n' +
    '  return { version: DATA.version, match: match, get: get, svg: svg, all: function () { return DATA.brands.slice(); } };\n' +
    '})();\nwindow.FH_BRANDS = FH_BRANDS;';
}

function generate() {
  const { reg, glyphs } = load();
  const out = path.join(ROOT, 'src', 'js-ui', '08-brands.js');
  const text = clientJs(reg, glyphs);
  if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== text) fs.writeFileSync(out, text);
  return reg.brands.length;
}
if (require.main === module) console.log('gen-brands: ' + generate() + ' brands');
module.exports = { generate };
