# GENERATED by `make sync-shared` from shared/notify.py — do not edit.
"""Best-effort notifications to Telegram.

For watching a pipeline in the days after it goes live, when tailing Cloud
Logging is not something anyone actually does. Off unless both
TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID are set.

Nothing here may raise. A notification that fails must not fail the delivery
that triggered it: Pub/Sub would redeliver the message, and the work would be
repeated for the sake of a status line. Every error is logged and swallowed.
"""

import json
import logging
import os
import urllib.error
import urllib.request

log = logging.getLogger(__name__)

_API = "https://api.telegram.org/bot{token}/sendMessage"

# Short on purpose. This runs inside a function with a 60s deadline that has
# real work to finish; a hanging notification must not eat that budget.
_TIMEOUT_SECONDS = 5


def enabled() -> bool:
    return bool(os.environ.get("TELEGRAM_BOT_TOKEN") and os.environ.get("TELEGRAM_CHAT_ID"))


def send(text: str) -> bool:
    """Post a message. Returns whether it went out; never raises."""
    token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    if not token or not chat_id:
        return False

    payload = json.dumps(
        {
            "chat_id": chat_id,
            "text": text,
            "parse_mode": "HTML",
            "disable_web_page_preview": True,
        }
    ).encode()

    request = urllib.request.Request(  # noqa: S310 - fixed https endpoint
        _API.format(token=token),
        data=payload,
        headers={"Content-Type": "application/json"},
    )

    try:
        with urllib.request.urlopen(request, timeout=_TIMEOUT_SECONDS) as response:  # noqa: S310
            if response.status == 200:
                return True
            log.warning("telegram returned HTTP %s", response.status)
    except urllib.error.HTTPError as exc:
        # The body carries Telegram's reason (bad chat_id, bot blocked, ...).
        # The token is in the URL, so log the reason, never the request.
        log.warning("telegram rejected the message: HTTP %s", exc.code)
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        log.warning("telegram unreachable: %s", type(exc).__name__)
    return False


def escape(text: str) -> str:
    """Escape the three characters Telegram's HTML mode treats as markup.

    Subjects come from email and are attacker-controlled; an unescaped "<"
    would break the message or let a sender inject formatting.
    """
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
